parameters:
#    onemedia_mongo.example.class: Onemedia\MongoBundle\Example

services:
#    onemedia_mongo.example:
#        class: %onemedia_mongo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
